from django.urls import path

from core.views import (
    accept_invite_view,
    check_invite_by_email_view,
    forgot_password_view,
    impersonate_exit_view,
    impersonate_start_view,
    impersonate_users_view,
    change_order_contract_view,
    change_order_detail_view,
    change_order_status_events_view,
    public_change_order_decision_view,
    public_change_order_detail_view,
    cost_code_detail_view,
    cost_codes_import_csv_view,
    cost_codes_list_create_view,
    customer_detail_view,
    customer_project_create_view,
    customers_list_view,
    estimate_clone_version_view,
    estimate_contract_view,
    estimate_duplicate_view,
    estimate_detail_view,
    estimate_status_events_view,
    public_estimate_decision_view,
    public_estimate_detail_view,
    public_request_otp_view,
    public_verify_otp_view,
    health_view,
    invoice_detail_view,
    invoice_contract_view,
    invoice_send_view,
    public_invoice_decision_view,
    invoice_status_events_view,
    public_invoice_detail_view,
    login_view,
    me_view,
    register_view,
    resend_verification_view,
    reset_password_view,
    verify_email_view,
    verify_invite_view,
    organization_invite_detail_view,
    organization_invites_view,
    organization_membership_detail_view,
    organization_memberships_view,
    organization_logo_upload_view,
    organization_profile_view,
    complete_onboarding_view,
    accounting_sync_event_retry_view,
    attention_feed_view,
    change_impact_summary_view,
    org_invoices_view,
    org_payments_view,
    org_stores_view,
    org_vendor_bills_view,
    project_expenses_view,
    receipt_scan_view,
    payment_detail_view,
    payment_contract_view,
    project_change_orders_view,
    project_estimates_view,
    project_invoices_view,
    project_payments_view,
    project_vendor_bills_view,
    portfolio_snapshot_view,
    project_detail_view,
    project_accounting_export_view,
    project_audit_events_view,
    project_contract_breakdown_view,
    project_timeline_events_view,
    project_accounting_sync_events_view,
    project_financial_summary_view,
    quick_jump_search_view,
    projects_list_view,
    push_status_view,
    push_subscribe_view,
    push_unsubscribe_view,
    quick_add_customer_intake_view,
    vendor_bill_detail_view,
    vendor_bill_contract_view,
    vendor_bill_snapshots_view,
    vendor_detail_view,
    vendors_import_csv_view,
    vendors_list_create_view,
)

urlpatterns = [
    path("health/", health_view, name="health"),
    path("auth/login/", login_view, name="auth-login"),
    path("auth/register/", register_view, name="auth-register"),
    path("auth/me/", me_view, name="auth-me"),
    path("auth/verify-invite/<str:token>/", verify_invite_view, name="auth-verify-invite"),
    path("auth/accept-invite/", accept_invite_view, name="auth-accept-invite"),
    path("auth/verify-email/", verify_email_view, name="auth-verify-email"),
    path("auth/resend-verification/", resend_verification_view, name="auth-resend-verification"),
    path("auth/forgot-password/", forgot_password_view, name="auth-forgot-password"),
    path("auth/reset-password/", reset_password_view, name="auth-reset-password"),
    path("auth/check-invite/", check_invite_by_email_view, name="auth-check-invite"),
    path("admin/impersonate/", impersonate_start_view, name="admin-impersonate-start"),
    path("admin/impersonate/exit/", impersonate_exit_view, name="admin-impersonate-exit"),
    path("admin/impersonate/users/", impersonate_users_view, name="admin-impersonate-users"),
    path("organization/", organization_profile_view, name="organization-profile"),
    path("organization/logo/", organization_logo_upload_view, name="organization-logo-upload"),
    path("organization/complete-onboarding/", complete_onboarding_view, name="organization-complete-onboarding"),
    path(
        "organization/invites/",
        organization_invites_view,
        name="organization-invites",
    ),
    path(
        "organization/invites/<int:invite_id>/",
        organization_invite_detail_view,
        name="organization-invite-detail",
    ),
    path(
        "organization/memberships/",
        organization_memberships_view,
        name="organization-memberships",
    ),
    path(
        "organization/memberships/<int:membership_id>/",
        organization_membership_detail_view,
        name="organization-membership-detail",
    ),
    path("push/subscribe/", push_subscribe_view, name="push-subscribe"),
    path("push/unsubscribe/", push_unsubscribe_view, name="push-unsubscribe"),
    path("push/status/", push_status_view, name="push-status"),
    path("customers/quick-add/", quick_add_customer_intake_view, name="customers-quick-add"),
    # Canonical customer-management routes.
    path("customers/", customers_list_view, name="customers-list"),
    path("customers/<int:customer_id>/", customer_detail_view, name="customers-detail"),
    path(
        "customers/<int:customer_id>/projects/",
        customer_project_create_view,
        name="customers-projects-create",
    ),
    path("projects/", projects_list_view, name="projects-list"),
    path("search/quick-jump/", quick_jump_search_view, name="search-quick-jump"),
    path("reports/attention-feed/", attention_feed_view, name="reports-attention-feed"),
    path("reports/portfolio/", portfolio_snapshot_view, name="reports-portfolio"),
    path("reports/change-impact/", change_impact_summary_view, name="reports-change-impact"),
    path("projects/<int:project_id>/", project_detail_view, name="project-detail"),
    path(
        "projects/<int:project_id>/financial-summary/",
        project_financial_summary_view,
        name="project-financial-summary",
    ),
    path(
        "projects/<int:project_id>/contract-breakdown/",
        project_contract_breakdown_view,
        name="project-contract-breakdown",
    ),
    path(
        "projects/<int:project_id>/audit-events/",
        project_audit_events_view,
        name="project-audit-events",
    ),
    path(
        "projects/<int:project_id>/timeline/",
        project_timeline_events_view,
        name="project-timeline-events",
    ),
    path(
        "projects/<int:project_id>/accounting-export/",
        project_accounting_export_view,
        name="project-accounting-export",
    ),
    path(
        "projects/<int:project_id>/accounting-sync-events/",
        project_accounting_sync_events_view,
        name="project-accounting-sync-events",
    ),
    path(
        "projects/<int:project_id>/estimates/",
        project_estimates_view,
        name="project-estimates",
    ),
    path(
        "projects/<int:project_id>/change-orders/",
        project_change_orders_view,
        name="project-change-orders",
    ),
    path(
        "contracts/change-orders/",
        change_order_contract_view,
        name="contracts-change-orders",
    ),
    path(
        "contracts/estimates/",
        estimate_contract_view,
        name="contracts-estimates",
    ),
    path(
        "projects/<int:project_id>/invoices/",
        project_invoices_view,
        name="project-invoices",
    ),
    path(
        "contracts/invoices/",
        invoice_contract_view,
        name="contracts-invoices",
    ),
    path(
        "projects/<int:project_id>/expenses/",
        project_expenses_view,
        name="project-expenses",
    ),
    path(
        "projects/<int:project_id>/vendor-bills/",
        project_vendor_bills_view,
        name="project-vendor-bills",
    ),
    path(
        "contracts/vendor-bills/",
        vendor_bill_contract_view,
        name="contracts-vendor-bills",
    ),
    path(
        "projects/<int:project_id>/payments/",
        project_payments_view,
        name="project-payments",
    ),
    path(
        "contracts/payments/",
        payment_contract_view,
        name="contracts-payments",
    ),
    path("estimates/<int:estimate_id>/", estimate_detail_view, name="estimate-detail"),
    path(
        "public/estimates/<str:public_token>/",
        public_estimate_detail_view,
        name="public-estimate-detail",
    ),
    path(
        "public/estimates/<str:public_token>/decision/",
        public_estimate_decision_view,
        name="public-estimate-decision",
    ),
    path(
        "public/change-orders/<str:public_token>/",
        public_change_order_detail_view,
        name="public-change-order-detail",
    ),
    path(
        "public/change-orders/<str:public_token>/decision/",
        public_change_order_decision_view,
        name="public-change-order-decision",
    ),
    path(
        "public/invoices/<str:public_token>/",
        public_invoice_detail_view,
        name="public-invoice-detail",
    ),
    path(
        "public/invoices/<str:public_token>/decision/",
        public_invoice_decision_view,
        name="public-invoice-decision",
    ),
    # -- Generic OTP routes (document_type validated by handler) --
    path(
        "public/<str:document_type>/<str:public_token>/otp/",
        public_request_otp_view,
        name="public-request-otp",
    ),
    path(
        "public/<str:document_type>/<str:public_token>/otp/verify/",
        public_verify_otp_view,
        name="public-verify-otp",
    ),
    path(
        "estimates/<int:estimate_id>/status-events/",
        estimate_status_events_view,
        name="estimate-status-events",
    ),
    path(
        "estimates/<int:estimate_id>/clone-version/",
        estimate_clone_version_view,
        name="estimate-clone-version",
    ),
    path(
        "estimates/<int:estimate_id>/duplicate/",
        estimate_duplicate_view,
        name="estimate-duplicate",
    ),
    path(
        "change-orders/<int:change_order_id>/",
        change_order_detail_view,
        name="change-order-detail",
    ),
    path(
        "change-orders/<int:change_order_id>/status-events/",
        change_order_status_events_view,
        name="change-order-status-events",
    ),
    path("invoices/<int:invoice_id>/", invoice_detail_view, name="invoice-detail"),
    path("invoices/<int:invoice_id>/send/", invoice_send_view, name="invoice-send"),
    path(
        "invoices/<int:invoice_id>/status-events/",
        invoice_status_events_view,
        name="invoice-status-events",
    ),
    path(
        "vendor-bills/<int:vendor_bill_id>/",
        vendor_bill_detail_view,
        name="vendor-bill-detail",
    ),
    path(
        "vendor-bills/<int:vendor_bill_id>/snapshots/",
        vendor_bill_snapshots_view,
        name="vendor-bill-snapshots",
    ),
    path("payments/", org_payments_view, name="org-payments"),
    path("payments/<int:payment_id>/", payment_detail_view, name="payment-detail"),
    path("invoices/", org_invoices_view, name="org-invoices"),
    path("vendor-bills/", org_vendor_bills_view, name="org-vendor-bills"),
    path("stores/", org_stores_view, name="org-stores"),
    path("vendor-bills/scan/", receipt_scan_view, name="vendor-bill-scan"),
    path(
        "accounting-sync-events/<int:sync_event_id>/retry/",
        accounting_sync_event_retry_view,
        name="accounting-sync-event-retry",
    ),
    path("vendors/", vendors_list_create_view, name="vendors-list-create"),
    path("vendors/import-csv/", vendors_import_csv_view, name="vendors-import-csv"),
    path("vendors/<int:vendor_id>/", vendor_detail_view, name="vendors-detail"),
    path("cost-codes/", cost_codes_list_create_view, name="cost-codes-list-create"),
    path("cost-codes/import-csv/", cost_codes_import_csv_view, name="cost-codes-import-csv"),
    path("cost-codes/<int:cost_code_id>/", cost_code_detail_view, name="cost-codes-detail"),
]
