"""Canonical system RoleTemplate definitions for RBAC seeding.

Used by the initial migration (RunPython) and management commands
(seed_adoption_stages, reset_fresh_demo) to ensure consistent role
template data across all entry points.
"""

SYSTEM_ROLES = {
    "owner": {
        "name": "Owner",
        "description": "Full access to everything.",
        "capability_flags_json": {
            "quotes": ["view", "create", "edit", "approve", "send"],
            "change_orders": ["view", "create", "edit", "approve", "send"],
            "invoices": ["view", "create", "edit", "approve", "send"],
            "vendor_bills": ["view", "create", "edit", "approve", "pay"],
            "projects": ["view", "create", "edit"],
            "customers": ["view", "create", "edit", "disable"],
            "cost_codes": ["view", "create", "edit", "disable"],
            "vendors": ["view", "create", "edit", "disable"],
            "org_identity": ["view", "edit"],
            "org_presets": ["view", "edit"],
            "users": ["view", "invite", "edit_role", "disable"],
            "payments": ["view", "create", "edit", "allocate"],
            "accounting_sync": ["view", "create", "retry"],
        },
    },
    "pm": {
        "name": "Project Manager",
        "description": "Full access except org identity editing.",
        "capability_flags_json": {
            "quotes": ["view", "create", "edit", "approve", "send"],
            "change_orders": ["view", "create", "edit", "approve", "send"],
            "invoices": ["view", "create", "edit", "approve", "send"],
            "vendor_bills": ["view", "create", "edit", "approve", "pay"],
            "projects": ["view", "create", "edit"],
            "customers": ["view", "create", "edit", "disable"],
            "cost_codes": ["view", "create", "edit", "disable"],
            "vendors": ["view", "create", "edit", "disable"],
            "org_identity": ["view"],
            "org_presets": ["view", "edit"],
            "users": ["view", "invite", "edit_role", "disable"],
            "payments": ["view", "create", "edit", "allocate"],
            "accounting_sync": ["view"],
        },
    },
    "worker": {
        "name": "Worker",
        "description": "Day-to-day document work. No approve, pay, disable, or user management.",
        "capability_flags_json": {
            "quotes": ["view", "create", "edit", "send"],
            "change_orders": ["view", "create", "edit", "send"],
            "invoices": ["view", "create", "edit", "send"],
            "vendor_bills": ["view", "create", "edit"],
            "projects": ["view", "create", "edit"],
            "customers": ["view", "create", "edit"],
            "cost_codes": ["view", "create", "edit"],
            "vendors": ["view", "create", "edit"],
            "org_identity": ["view"],
            "org_presets": ["view"],
            "users": [],
            "payments": ["view"],
            "accounting_sync": ["view"],
        },
    },
    "bookkeeping": {
        "name": "Bookkeeping",
        "description": "Financial record-keeper. Full vendor bills, invoices without send.",
        "capability_flags_json": {
            "quotes": ["view"],
            "change_orders": ["view"],
            "invoices": ["view", "create", "edit"],
            "vendor_bills": ["view", "create", "edit", "approve", "pay"],
            "projects": ["view"],
            "customers": ["view"],
            "cost_codes": ["view", "create", "edit"],
            "vendors": ["view", "create", "edit"],
            "org_identity": ["view"],
            "org_presets": ["view"],
            "users": [],
            "payments": ["view", "create", "edit", "allocate"],
            "accounting_sync": ["view", "create", "retry"],
        },
    },
    "viewer": {
        "name": "Viewer",
        "description": "Read-only access across all resources.",
        "capability_flags_json": {
            "quotes": ["view"],
            "change_orders": ["view"],
            "invoices": ["view"],
            "vendor_bills": ["view"],
            "projects": ["view"],
            "customers": ["view"],
            "cost_codes": ["view"],
            "vendors": ["view"],
            "org_identity": ["view"],
            "org_presets": ["view"],
            "users": [],
            "payments": ["view"],
            "accounting_sync": ["view"],
        },
    },
}
