# Generated by Django 6.0.2 on 2026-03-08 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
    ]
