# Generated by Django 6.0.2 on 2026-03-08 23:29

from django.db import migrations, models


def backfill_existing_orgs(apps, schema_editor):
    """Existing orgs predate onboarding — mark them as completed."""
    Organization = apps.get_model("core", "Organization")
    Organization.objects.all().update(onboarding_completed=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(backfill_existing_orgs, migrations.RunPython.noop),
    ]
