# Generated by Django 6.0.3 on 2026-04-10 23:54

from django.db import migrations, models


def create_heartbeat_schedule(apps, schema_editor):
    """Create the recurring heartbeat task in django-q2."""
    Schedule = apps.get_model("django_q", "Schedule")
    Schedule.objects.update_or_create(
        name="worker-heartbeat",
        defaults={
            "func": "core.tasks.worker_heartbeat_task",
            "schedule_type": "I",  # Schedule.MINUTES
            "minutes": 5,
            "repeats": -1,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('django_q', '__latest__'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen', models.DateTimeField()),
            ],
            options={
                'db_table': 'worker_heartbeat',
            },
        ),
        migrations.RunPython(create_heartbeat_schedule, migrations.RunPython.noop),
    ]
