# Generated by Django 6.0.3 on 2026-04-02 01:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='changeorder',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='costcode',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='quote',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='changeorder',
            constraint=models.UniqueConstraint(fields=('project', 'family_key'), name='unique_co_family_key_per_project'),
        ),
        migrations.AddConstraint(
            model_name='costcode',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_cost_code_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('project', 'invoice_number'), name='unique_invoice_number_per_project'),
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.UniqueConstraint(fields=('project', 'title', 'version'), name='unique_quote_title_version_per_project'),
        ),
    ]
