# Generated by Django 6.0.3 on 2026-04-02 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_upgrade_unique_together_to_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorBillStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('open', 'Open'), ('disputed', 'Disputed'), ('closed', 'Closed'), ('void', 'Void')], max_length=32, null=True)),
                ('to_status', models.CharField(choices=[('open', 'Open'), ('disputed', 'Disputed'), ('closed', 'Closed'), ('void', 'Void')], max_length=32)),
                ('note', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_bill_status_events', to=settings.AUTH_USER_MODEL)),
                ('vendor_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='core.vendorbill')),
            ],
            options={
                'ordering': ['-changed_at', '-id'],
            },
        ),
    ]
