# Generated by Django 6.0.2 on 2026-02-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_invoice_footer_text_invoice_notes_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='terms_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='organization',
            name='estimate_default_terms',
            field=models.TextField(blank=True, default=''),
        ),
    ]
