# Generated by Django 6.0.2 on 2026-03-08 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_costcode_organization_nonnull'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='logo_url',
        ),
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, default='', upload_to='logos/'),
        ),
    ]
