# Generated by Django 6.0.2 on 2026-02-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_estimate_terms_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='change_order_default_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
