# Generated by Django 6.0.2 on 2026-03-08 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_logo_image_field'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='changeorderline',
            name='co_line_unique_budget_line_per_change_order',
        ),
        migrations.RemoveConstraint(
            model_name='changeorderline',
            name='co_line_adjustment_requires_reason',
        ),
        migrations.AddField(
            model_name='changeorderline',
            name='cost_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='change_order_lines', to='core.costcode'),
        ),
        migrations.AlterField(
            model_name='changeorderline',
            name='budget_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='change_order_lines', to='core.budgetline'),
        ),
        migrations.AlterField(
            model_name='changeorderline',
            name='line_type',
            field=models.CharField(choices=[('original', 'Original'), ('new', 'New')], default='original', max_length=24),
        ),
    ]
