# Generated by Django 6.0.3 on 2026-03-24 05:10

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_invoice_related_estimate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='project',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='store',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='receipt',
        ),
        migrations.RemoveConstraint(
            model_name='store',
            name='uniq_store_name_per_org_ci',
        ),
        migrations.RemoveConstraint(
            model_name='vendorbill',
            name='uniq_active_vendor_bill_number_per_project_vendor_ci',
        ),
        migrations.AddField(
            model_name='vendorbill',
            name='store_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='target_type',
            field=models.CharField(blank=True, choices=[('invoice', 'Invoice'), ('vendor_bill', 'Vendor Bill')], default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='vendorbill',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendor_bills', to='core.vendor'),
        ),
        migrations.AddConstraint(
            model_name='vendorbill',
            constraint=models.UniqueConstraint(models.F('project'), models.F('vendor'), django.db.models.functions.text.Lower('bill_number'), condition=models.Q(models.Q(('status', 'void'), _negated=True), models.Q(('bill_number', ''), _negated=True), ('vendor__isnull', False)), name='uniq_active_vendor_bill_number_per_project_vendor_ci'),
        ),
        migrations.DeleteModel(
            name='Receipt',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
