# Generated by Django 4.2 on 2026-02-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_changeorder"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="approved_change_order_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
