# Generated by Django 6.0.2 on 2026-03-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_payment_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('ach', 'ACH'), ('card', 'Card'), ('check', 'Check'), ('wire', 'Wire'), ('zelle', 'Zelle'), ('cash', 'Cash'), ('other', 'Other')], max_length=16),
        ),
    ]
