# Generated by Django 6.0.2 on 2026-03-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_organization_identity_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceline',
            name='line_type',
            field=models.CharField(choices=[('scope', 'Scope'), ('adjustment', 'Adjustment'), ('direct', 'Direct')], default='scope', max_length=24),
        ),
    ]
