# Generated by Django 6.0.2 on 2026-03-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_invoice_direct_line_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('settled', 'Settled'), ('void', 'Void')], default='settled', max_length=16),
        ),
        migrations.AlterField(
            model_name='paymentallocationrecord',
            name='capture_source',
            field=models.CharField(choices=[('manual_ui', 'Manual UI'), ('manual_api', 'Manual API'), ('system', 'System')], max_length=32),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='capture_source',
            field=models.CharField(choices=[('manual_ui', 'Manual UI'), ('manual_api', 'Manual API'), ('system', 'System')], max_length=32),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('status_changed', 'Status Changed'), ('allocation_applied', 'Allocation Applied')], max_length=32),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='from_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('settled', 'Settled'), ('void', 'Void')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='to_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('settled', 'Settled'), ('void', 'Void')], max_length=32, null=True),
        ),
    ]
