# Generated by Django 6.0.3 on 2026-03-24 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_restore_store_model_vendor_bill_store_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorbill',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('disputed', 'Disputed'), ('closed', 'Closed'), ('void', 'Void')], db_index=True, default='open', max_length=32),
        ),
        migrations.AlterField(
            model_name='vendorbillsnapshot',
            name='capture_status',
            field=models.CharField(choices=[('open', 'Open'), ('disputed', 'Disputed'), ('closed', 'Closed'), ('void', 'Void')], max_length=32),
        ),
    ]
