# Generated by Django 6.0.2 on 2026-03-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_payment_method_zelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeordersnapshot',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='changeordersnapshot',
            name='user_agent',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='estimatestatusevent',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estimatestatusevent',
            name='user_agent',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='invoicestatusevent',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicestatusevent',
            name='user_agent',
            field=models.TextField(blank=True, default=''),
        ),
    ]
