# Generated by Django 6.0.2 on 2026-03-14 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_audit_metadata_to_status_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeorder',
            name='sender_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='changeorder',
            name='sender_logo_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='changeorder',
            name='sender_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='estimate',
            name='sender_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='estimate',
            name='sender_logo_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='estimate',
            name='sender_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
