# Generated by Django 6.0.3 on 2026-03-24 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_vendor_bill_open_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='changeorder',
            unique_together={('project', 'family_key')},
        ),
        migrations.RemoveField(
            model_name='changeorder',
            name='previous_change_order',
        ),
        migrations.RemoveField(
            model_name='changeorder',
            name='revision_number',
        ),
    ]
