# Generated by Django 6.0.2 on 2026-03-06 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_email_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAccessSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('estimate', 'Estimate'), ('change_order', 'Change Order'), ('invoice', 'Invoice')], max_length=20)),
                ('document_id', models.PositiveIntegerField()),
                ('public_token', models.CharField(db_index=True, max_length=24)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=6)),
                ('session_token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('session_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SigningCeremonyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('estimate', 'Estimate'), ('change_order', 'Change Order'), ('invoice', 'Invoice')], max_length=20)),
                ('document_id', models.PositiveIntegerField()),
                ('public_token', models.CharField(max_length=24)),
                ('decision', models.CharField(max_length=20)),
                ('signer_name', models.CharField(max_length=200)),
                ('signer_email', models.CharField(max_length=254)),
                ('email_verified', models.BooleanField(default=True)),
                ('content_hash', models.CharField(max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('consent_text_version', models.CharField(max_length=64)),
                ('consent_text_snapshot', models.TextField()),
                ('note', models.TextField(blank=True, default='')),
                ('ceremony_completed_at', models.DateTimeField()),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('access_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signing_ceremonies', to='core.documentaccesssession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
