# Generated by Django 6.0.2 on 2026-03-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_sender_identity_fields_to_estimate_and_change_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('check', 'Check'), ('zelle', 'Zelle'), ('ach', 'ACH'), ('cash', 'Cash'), ('wire', 'Wire'), ('card', 'Card'), ('other', 'Other')], max_length=16),
        ),
    ]
