# Generated by Django 6.0.3 on 2026-03-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_co_revision_chain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailrecord',
            name='email_type',
            field=models.CharField(choices=[('verification', 'Verification'), ('password_reset', 'Password Reset'), ('otp', 'OTP'), ('document_sent', 'Document Sent'), ('document_decision', 'Document Decision')], max_length=32),
        ),
    ]
