# Generated by Django 6.0.2 on 2026-03-16 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='public_token',
            field=models.CharField(blank=True, max_length=24, null=True, unique=True),
        ),
    ]
