# Generated by Django 6.0.2 on 2026-03-06 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_public_signing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailrecord',
            name='email_type',
            field=models.CharField(choices=[('verification', 'Verification'), ('otp', 'OTP')], max_length=32),
        ),
    ]
