# Generated by Django 6.0.3 on 2026-03-25 01:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_emailrecord_email_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('customer', 'name'), name='unique_project_name_per_customer'),
        ),
    ]
