# Generated by Django 6.0.2 on 2026-03-01 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_organization_help_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='end_date_planned',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_date_planned',
        ),
    ]
