# Generated by Django 6.0.2 on 2026-03-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_project_planned_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeorder',
            name='terms_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='organization',
            name='change_order_default_terms',
            field=models.TextField(blank=True, default=''),
        ),
    ]
