# Generated by Django 6.0.2 on 2026-03-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_estimate_public_token_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('void', 'Void')], db_index=True, default='draft', max_length=32),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('void', 'Void'), ('archived', 'Archived')], db_index=True, default='draft', max_length=32),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('void', 'Void')], db_index=True, default='draft', max_length=32),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('settled', 'Settled'), ('void', 'Void')], db_index=True, default='settled', max_length=16),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('prospect', 'Prospect'), ('active', 'Active'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='prospect', max_length=32),
        ),
        migrations.AlterField(
            model_name='vendorbill',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('received', 'Received'), ('approved', 'Approved'), ('scheduled', 'Scheduled'), ('paid', 'Paid'), ('void', 'Void')], db_index=True, default='planned', max_length=32),
        ),
    ]
