# Generated by Django 6.0.2 on 2026-03-06 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_email_type_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentaccesssession',
            name='failed_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
