# Generated by Django 6.0.2 on 2026-03-16 11:08

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_status_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vendorbill',
            name='uniq_active_vendor_bill_number_per_project_vendor_ci',
        ),
        migrations.AddField(
            model_name='vendorbill',
            name='cost_code',
            field=models.ForeignKey(blank=True, help_text='Optional cost code for the entire bill/receipt (receipts without line items).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendor_bills', to='core.costcode'),
        ),
        migrations.AddField(
            model_name='vendorbill',
            name='kind',
            field=models.CharField(choices=[('bill', 'Bill'), ('receipt', 'Receipt')], db_index=True, default='bill', max_length=16),
        ),
        migrations.AlterField(
            model_name='vendorbill',
            name='bill_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='vendorbill',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendorbill',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendorbill',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('received', 'Received'), ('approved', 'Approved'), ('scheduled', 'Scheduled'), ('paid', 'Paid'), ('void', 'Void'), ('recorded', 'Recorded')], db_index=True, default='planned', max_length=32),
        ),
        migrations.AlterField(
            model_name='vendorbill',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendor_bills', to='core.vendor'),
        ),
        migrations.AddConstraint(
            model_name='vendorbill',
            constraint=models.UniqueConstraint(models.F('project'), models.F('vendor'), django.db.models.functions.text.Lower('bill_number'), condition=models.Q(models.Q(('status', 'void'), _negated=True), models.Q(('bill_number', ''), _negated=True)), name='uniq_active_vendor_bill_number_per_project_vendor_ci'),
        ),
    ]
