# Generated by Django 6.0.2 on 2026-03-02 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_terms_text_to_change_order_and_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorbill',
            name='received_date',
            field=models.DateField(blank=True, help_text='Date the bill was physically received. Distinct from vendor issue date.', null=True),
        ),
        migrations.AddField(
            model_name='vendorbill',
            name='shipping_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='vendorbill',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='vendorbill',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
