# Generated by Django 6.0.2 on 2026-03-17 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_vendor_bill_receipt_support'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorbillline',
            old_name='line_total',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='vendorbill',
            name='scheduled_for',
        ),
        migrations.RemoveField(
            model_name='vendorbillline',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='vendorbillline',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='vendorbillline',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='cost_code',
            field=models.ForeignKey(blank=True, help_text='Authoritative cost attribution — classified at payment time for profitability metrics.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='core.costcode'),
        ),
        migrations.AlterField(
            model_name='vendorbill',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('disputed', 'Disputed'), ('closed', 'Closed'), ('void', 'Void'), ('recorded', 'Recorded')], db_index=True, default='received', max_length=32),
        ),
        migrations.AlterField(
            model_name='vendorbillsnapshot',
            name='capture_status',
            field=models.CharField(choices=[('received', 'Received'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('disputed', 'Disputed'), ('closed', 'Closed'), ('void', 'Void')], max_length=32),
        ),
    ]
