# Generated by Django 6.0.2 on 2026-03-17 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_ap_model_separation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorbill',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('approved', 'Approved'), ('disputed', 'Disputed'), ('closed', 'Closed'), ('void', 'Void'), ('recorded', 'Recorded')], db_index=True, default='received', max_length=32),
        ),
        migrations.AlterField(
            model_name='vendorbillsnapshot',
            name='capture_status',
            field=models.CharField(choices=[('received', 'Received'), ('approved', 'Approved'), ('disputed', 'Disputed'), ('closed', 'Closed'), ('void', 'Void')], max_length=32),
        ),
    ]
