# Generated by Django 6.0.3 on 2026-03-29 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_invoice_status_outstanding_closed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QBOConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realm_id', models.CharField(help_text='QBO company ID (realmId from OAuth callback).', max_length=64)),
                ('_access_token', models.TextField(db_column='access_token', help_text='Fernet-encrypted OAuth2 access token.')),
                ('_refresh_token', models.TextField(db_column='refresh_token', help_text='Fernet-encrypted OAuth2 refresh token.')),
                ('access_token_expires_at', models.DateTimeField(help_text='When the current access token expires.')),
                ('refresh_token_expires_at', models.DateTimeField(help_text='When the refresh token expires (~100 days from issue).')),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('connected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qbo_connection', to='core.organization')),
            ],
            options={
                'verbose_name': 'QBO Connection',
                'verbose_name_plural': 'QBO Connections',
                'db_table': 'core_qboconnection',
            },
        ),
    ]
