# Generated by Django 6.0.2 on 2026-02-15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_accountingsyncevent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialAuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("estimate_status_changed", "Estimate Status Changed"),
                            ("budget_converted", "Budget Converted"),
                            ("change_order_updated", "Change Order Updated"),
                            ("invoice_updated", "Invoice Updated"),
                            ("vendor_bill_updated", "Vendor Bill Updated"),
                            ("payment_updated", "Payment Updated"),
                            ("payment_allocated", "Payment Allocated"),
                            ("invoice_scope_override", "Invoice Scope Override"),
                        ],
                        max_length=64,
                    ),
                ),
                ("object_type", models.CharField(max_length=64)),
                ("object_id", models.PositiveIntegerField()),
                ("from_status", models.CharField(blank=True, max_length=32)),
                ("to_status", models.CharField(blank=True, max_length=32)),
                (
                    "amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("note", models.TextField(blank=True)),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="financial_audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="financial_audit_events",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
