# Generated by Django 6.0.3 on 2026-03-29 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_qbo_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='notes_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
