# Generated by Django 6.0.2 on 2026-02-16 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_financialauditevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leadcontact",
            name="phone",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
