# Generated by Django 6.0.2 on 2026-03-17 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_reviewed_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorbill',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('approved', 'Approved'), ('disputed', 'Disputed'), ('closed', 'Closed'), ('void', 'Void')], db_index=True, default='received', max_length=32),
        ),
    ]
