# Generated by Django 6.0.2 on 2026-02-16 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alter_leadcontact_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="leadcontact",
            name="initial_contract_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
