# Generated by Django 6.0.3 on 2026-03-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_estimate_notes_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcode',
            name='taxable',
            field=models.BooleanField(default=True),
        ),
    ]
