# Generated by Django 6.0.2 on 2026-02-19 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_leadcontact_initial_contract_value"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="estimate",
            unique_together={("project", "title", "version")},
        ),
    ]
