# Generated by Django 6.0.3 on 2026-03-29 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_cost_code_taxable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estimatelineitem',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='estimatelineitem',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='EstimateSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.estimate')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
