# Generated by Django 6.0.2 on 2026-03-17 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_receipt_vendor_separation'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentallocation',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_allocations', to='core.receipt'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='balance_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='paymentallocation',
            name='target_type',
            field=models.CharField(choices=[('invoice', 'Invoice'), ('vendor_bill', 'Vendor Bill'), ('receipt', 'Receipt')], max_length=16),
        ),
        migrations.AlterField(
            model_name='paymentallocationrecord',
            name='target_type',
            field=models.CharField(choices=[('invoice', 'Invoice'), ('vendor_bill', 'Vendor Bill'), ('receipt', 'Receipt')], max_length=16),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='store',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
