# Generated by Django 6.0.2 on 2026-02-19 00:48

import secrets
import string

from django.db import migrations, models


def _generate_public_token(length=12):
    alphabet = string.ascii_letters + string.digits
    return "".join(secrets.choice(alphabet) for _ in range(length))


def backfill_public_tokens(apps, schema_editor):
    Estimate = apps.get_model("core", "Estimate")
    used = set(
        Estimate.objects.exclude(public_token__isnull=True)
        .exclude(public_token="")
        .values_list("public_token", flat=True)
    )
    for estimate in Estimate.objects.filter(public_token__isnull=True).iterator():
        candidate = _generate_public_token()
        while candidate in used:
            candidate = _generate_public_token()
        used.add(candidate)
        estimate.public_token = candidate
        estimate.save(update_fields=["public_token", "updated_at"])

    for estimate in Estimate.objects.filter(public_token="").iterator():
        candidate = _generate_public_token()
        while candidate in used:
            candidate = _generate_public_token()
        used.add(candidate)
        estimate.public_token = candidate
        estimate.save(update_fields=["public_token", "updated_at"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_alter_estimate_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="estimate",
            name="public_token",
            field=models.CharField(blank=True, max_length=24, null=True, unique=True),
        ),
        migrations.RunPython(backfill_public_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="estimate",
            name="public_token",
            field=models.CharField(blank=True, default="", max_length=24, unique=True),
        ),
    ]
