# Generated by Django 6.0.3 on 2026-03-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_vendorbillline_qty_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorbillsnapshot',
            name='status_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='vendorbill',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('disputed', 'Disputed'), ('approved', 'Approved'), ('closed', 'Closed'), ('void', 'Void')], db_index=True, default='received', max_length=32),
        ),
    ]
