# Generated by Django 6.0.3 on 2026-03-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_change_order_sections_and_line_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeorder',
            name='contract_pdf',
            field=models.FileField(blank=True, default='', upload_to='contracts/change-orders/'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='contract_pdf',
            field=models.FileField(blank=True, default='', upload_to='contracts/estimates/'),
        ),
    ]
