# Generated by Django 6.0.3 on 2026-03-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_contract_pdf_on_estimates_and_change_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='contingency_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='estimate',
            name='contingency_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='estimate',
            name='insurance_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='estimate',
            name='insurance_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='estimate',
            name='overhead_profit_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='estimate',
            name='overhead_profit_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
