# Generated by Django 6.0.3 on 2026-03-19 20:13
# Edited to include data migration from PaymentAllocation → Payment target FKs.

import django.db.models.deletion
from django.db import migrations, models


def copy_allocation_targets(apps, schema_editor):
    """Copy target info from each payment's allocation onto the payment itself.

    Since payments are 1:1 with allocations (one payment, one target), we take
    the first allocation for each payment and set the target FK + target_type.
    """
    PaymentAllocation = apps.get_model("core", "PaymentAllocation")
    Payment = apps.get_model("core", "Payment")

    for alloc in PaymentAllocation.objects.select_related("payment").all():
        payment = alloc.payment
        payment.target_type = alloc.target_type
        payment.invoice_id = alloc.invoice_id
        payment.vendor_bill_id = alloc.vendor_bill_id
        payment.receipt_id = alloc.receipt_id
        payment.save(update_fields=["target_type", "invoice_id", "vendor_bill_id", "receipt_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_vendor_bill_snapshot_status_note'),
    ]

    operations = [
        # Step 1: Add new target fields to Payment
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='target_payments', to='core.invoice'),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='target_payments', to='core.receipt'),
        ),
        migrations.AddField(
            model_name='payment',
            name='target_type',
            field=models.CharField(blank=True, choices=[('invoice', 'Invoice'), ('vendor_bill', 'Vendor Bill'), ('receipt', 'Receipt')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='payment',
            name='vendor_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='target_payments', to='core.vendorbill'),
        ),

        # Step 2: Copy target data from PaymentAllocation → Payment
        migrations.RunPython(copy_allocation_targets, migrations.RunPython.noop),

        # Step 3: Drop PaymentAllocationRecord FK dependencies first
        migrations.RemoveField(
            model_name='paymentallocationrecord',
            name='payment_allocation',
        ),
        migrations.RemoveField(
            model_name='paymentallocationrecord',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='paymentallocationrecord',
            name='recorded_by',
        ),

        # Step 4: Drop the old models
        migrations.DeleteModel(
            name='PaymentAllocation',
        ),
        migrations.DeleteModel(
            name='PaymentAllocationRecord',
        ),
    ]
