# Generated by Django 6.0.3 on 2026-03-21 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_drop_receipt_payment_fk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estimatelineitem',
            old_name='unit_cost',
            new_name='unit_price',
        ),
    ]
