# Generated by Django 6.0.2 on 2026-02-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_permission_roletemplate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="site_address",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
