# Generated by Django 6.0.2 on 2026-02-21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _backfill_vendor_organizations(apps, schema_editor):
    app_label, model_name = settings.AUTH_USER_MODEL.split(".")
    User = apps.get_model(app_label, model_name)
    Organization = apps.get_model("core", "Organization")
    OrganizationMembership = apps.get_model("core", "OrganizationMembership")
    Vendor = apps.get_model("core", "Vendor")

    active_memberships = {
        membership.user_id: membership
        for membership in OrganizationMembership.objects.filter(
            status="active",
        ).only("id", "user_id", "organization_id")
    }

    for vendor in Vendor.objects.filter(organization__isnull=True).only("id", "created_by_id"):
        membership = active_memberships.get(vendor.created_by_id)
        if not membership:
            user = User.objects.get(id=vendor.created_by_id)
            email_seed = (getattr(user, "email", "") or getattr(user, "username", "") or f"user-{user.id}")
            display_seed = email_seed.split("@")[0].replace(".", " ").replace("_", " ").replace("-", " ").strip()
            display_name = f"{display_seed.title() or 'New'} Organization"
            organization = Organization.objects.create(
                display_name=display_name,
                slug=None,
                created_by_id=user.id,
            )
            membership = OrganizationMembership.objects.create(
                organization_id=organization.id,
                user_id=user.id,
                role="owner",
                status="active",
            )
            active_memberships[user.id] = membership

        vendor.organization_id = membership.organization_id
        vendor.save(update_fields=["organization"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0032_alter_costcode_unique_together_costcode_organization_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vendors",
                to="core.organization",
            ),
        ),
        migrations.RunPython(_backfill_vendor_organizations, migrations.RunPython.noop),
    ]
