# Generated by Django 6.0.2 on 2026-02-22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0033_vendor_organization"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScopeItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("normalized_name", models.CharField(max_length=255)),
                ("unit", models.CharField(default="ea", max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cost_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scope_items",
                        to="core.costcode",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scope_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scope_items",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "id"],
                "unique_together": {("organization", "cost_code", "normalized_name", "unit")},
            },
        ),
        migrations.AddField(
            model_name="estimatelineitem",
            name="scope_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="estimate_line_items",
                to="core.scopeitem",
            ),
        ),
        migrations.AddField(
            model_name="budgetline",
            name="scope_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="budget_lines",
                to="core.scopeitem",
            ),
        ),
    ]
