# Generated by Django 6.0.2 on 2026-02-22

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0035_changeordersnapshot"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="changeorder",
            constraint=models.CheckConstraint(
                condition=Q(
                    status="approved",
                    approved_at__isnull=False,
                    approved_by__isnull=False,
                )
                | ~Q(status="approved"),
                name="co_approved_requires_actor_and_timestamp",
            ),
        ),
        migrations.AddConstraint(
            model_name="changeorder",
            constraint=models.CheckConstraint(
                condition=Q(
                    origin_estimate__isnull=False,
                    origin_estimate_version__isnull=False,
                )
                | Q(
                    origin_estimate__isnull=True,
                    origin_estimate_version__isnull=True,
                ),
                name="co_origin_estimate_pair_consistent",
            ),
        ),
        migrations.AddIndex(
            model_name="changeorder",
            index=models.Index(fields=["project", "number"], name="core_changeo_project_93576b_idx"),
        ),
        migrations.AddConstraint(
            model_name="changeorderline",
            constraint=models.UniqueConstraint(
                fields=("change_order", "budget_line"),
                name="co_line_unique_budget_line_per_change_order",
            ),
        ),
    ]
