# Generated by Django 6.0.2 on 2026-02-22

from django.db import migrations, models


def _backfill_change_order_family_key(apps, schema_editor):
    ChangeOrder = apps.get_model("core", "ChangeOrder")
    for row in ChangeOrder.objects.filter(family_key__isnull=True).only("id", "number"):
        row.family_key = str(row.number)
        row.save(update_fields=["family_key"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0036_changeorder_model_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="changeorder",
            name="family_key",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.RunPython(_backfill_change_order_family_key, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="changeorder",
            name="family_key",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name="changeorder",
            unique_together={("project", "family_key", "revision_number")},
        ),
        migrations.RemoveIndex(
            model_name="changeorder",
            name="core_changeo_project_93576b_idx",
        ),
        migrations.AddIndex(
            model_name="changeorder",
            index=models.Index(fields=["project", "family_key"], name="core_changeo_proj_fam_idx"),
        ),
    ]
