# Generated by Django 6.0.2 on 2026-02-22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0037_changeorder_family_key_add_and_backfill"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="changeorder",
            name="number",
        ),
    ]
