# Generated by Django 6.0.2 on 2026-02-22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0038_changeorder_remove_number"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="changeorder",
            name="co_origin_estimate_pair_consistent",
        ),
        migrations.RemoveField(
            model_name="changeorder",
            name="origin_estimate_version",
        ),
    ]
