# Generated by Django 6.0.2 on 2026-02-22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0039_remove_changeorder_origin_estimate_version"),
    ]

    operations = [
        migrations.RenameField(
            model_name="changeorder",
            old_name="supersedes_change_order",
            new_name="previous_change_order",
        ),
    ]
