# Generated by Django 6.0.2 on 2026-02-22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0040_rename_supersedes_change_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="changeordersnapshot",
            name="decision_status",
            field=models.CharField(
                choices=[
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("void", "Void"),
                ],
                max_length=32,
            ),
        ),
    ]
