# Generated by Django 6.0.2 on 2026-02-22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0041_changeordersnapshot_void_decision_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="changeordersnapshot",
            old_name="created_by",
            new_name="decided_by",
        ),
        migrations.AlterField(
            model_name="changeordersnapshot",
            name="decided_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="decided_change_order_snapshots",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
