# Generated by Django 6.0.2 on 2026-02-22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0042_rename_changeordersnapshot_created_by_to_decided_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="VendorBillSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "capture_status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("approved", "Approved"),
                            ("scheduled", "Scheduled"),
                            ("paid", "Paid"),
                            ("void", "Void"),
                        ],
                        max_length=32,
                    ),
                ),
                ("snapshot_json", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "acted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acted_vendor_bill_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor_bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="snapshots",
                        to="core.vendorbill",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
