# Generated by Django 4.2 on 2026-02-23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0043_vendorbillsnapshot"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(due_date__gte=models.F("issue_date")),
                name="invoice_due_date_on_or_after_issue_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(balance_due__gte=0),
                name="invoice_balance_due_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(status="paid", balance_due=0) | ~models.Q(status="paid"),
                name="invoice_paid_requires_zero_balance_due",
            ),
        ),
    ]
