# Generated by Django 4.2 on 2026-02-23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0044_invoice_model_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceline",
            name="adjustment_reason",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="invoiceline",
            name="internal_note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="invoiceline",
            name="line_type",
            field=models.CharField(
                choices=[("scope", "Scope"), ("adjustment", "Adjustment")],
                default="scope",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="invoiceline",
            name="scope_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoice_lines",
                to="core.scopeitem",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoiceline",
            constraint=models.CheckConstraint(
                condition=models.Q(line_type="adjustment", adjustment_reason__gt="")
                | ~models.Q(line_type="adjustment"),
                name="invoice_line_adjustment_requires_reason",
            ),
        ),
    ]
