# Generated by Django 6.0.2 on 2026-02-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_invoicestatusevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('void', 'Void'), ('archived', 'Archived')], default='draft', max_length=32),
        ),
        migrations.AlterField(
            model_name='estimatestatusevent',
            name='from_status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('sent', 'Sent'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('void', 'Void'), ('archived', 'Archived')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='estimatestatusevent',
            name='to_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('void', 'Void'), ('archived', 'Archived')], max_length=32),
        ),
    ]
