# Generated by Django 6.0.2 on 2026-02-23 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alter_estimate_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('status_changed', 'Status Changed'), ('allocation_applied', 'Allocation Applied'), ('imported', 'Imported'), ('synced', 'Synced')], max_length=32)),
                ('capture_source', models.CharField(choices=[('manual_ui', 'Manual UI'), ('manual_api', 'Manual API'), ('ach_webhook', 'ACH Webhook'), ('processor_sync', 'Processor Sync'), ('csv_import', 'CSV Import'), ('system', 'System')], max_length=32)),
                ('source_reference', models.CharField(blank=True, default='', max_length=128)),
                ('from_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('settled', 'Settled'), ('failed', 'Failed'), ('void', 'Void')], max_length=32, null=True)),
                ('to_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('settled', 'Settled'), ('failed', 'Failed'), ('void', 'Void')], max_length=32, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('snapshot_json', models.JSONField(default=dict)),
                ('metadata_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='core.payment')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recorded_payment_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
