# Generated by Django 6.0.2 on 2026-02-23 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_paymentrecord"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentAllocationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[("applied", "Applied"), ("reversed", "Reversed")],
                        max_length=32,
                    ),
                ),
                (
                    "capture_source",
                    models.CharField(
                        choices=[
                            ("manual_ui", "Manual UI"),
                            ("manual_api", "Manual API"),
                            ("ach_webhook", "ACH Webhook"),
                            ("processor_sync", "Processor Sync"),
                            ("csv_import", "CSV Import"),
                            ("system", "System"),
                        ],
                        max_length=32,
                    ),
                ),
                ("source_reference", models.CharField(blank=True, default="", max_length=128)),
                (
                    "target_type",
                    models.CharField(
                        choices=[("invoice", "Invoice"), ("vendor_bill", "Vendor Bill")],
                        max_length=16,
                    ),
                ),
                ("target_object_id", models.PositiveBigIntegerField()),
                ("applied_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("note", models.TextField(blank=True, default="")),
                ("snapshot_json", models.JSONField(default=dict)),
                ("metadata_json", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocation_records",
                        to="core.payment",
                    ),
                ),
                (
                    "payment_allocation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="records",
                        to="core.paymentallocation",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recorded_payment_allocation_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
