# Generated by Django 6.0.2 on 2026-02-23 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_accountingsyncrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationMembershipRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('status_changed', 'Status Changed'), ('role_changed', 'Role Changed'), ('role_template_changed', 'Role Template Changed'), ('capability_flags_updated', 'Capability Flags Updated')], max_length=32)),
                ('capture_source', models.CharField(choices=[('auth_bootstrap', 'Auth Bootstrap'), ('manual_ui', 'Manual UI'), ('manual_api', 'Manual API'), ('system', 'System')], max_length=32)),
                ('source_reference', models.CharField(blank=True, default='', max_length=128)),
                ('from_status', models.CharField(blank=True, choices=[('active', 'Active'), ('disabled', 'Disabled')], max_length=32, null=True)),
                ('to_status', models.CharField(blank=True, choices=[('active', 'Active'), ('disabled', 'Disabled')], max_length=32, null=True)),
                ('from_role', models.CharField(blank=True, choices=[('owner', 'Owner'), ('pm', 'Project Manager'), ('worker', 'Worker'), ('bookkeeping', 'Bookkeeping'), ('viewer', 'Viewer')], default='', max_length=32)),
                ('to_role', models.CharField(blank=True, choices=[('owner', 'Owner'), ('pm', 'Project Manager'), ('worker', 'Worker'), ('bookkeeping', 'Bookkeeping'), ('viewer', 'Viewer')], default='', max_length=32)),
                ('note', models.TextField(blank=True, default='')),
                ('snapshot_json', models.JSONField(default=dict)),
                ('metadata_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('membership_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membership_subject_records', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organization_membership_records', to='core.organization')),
                ('organization_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='core.organizationmembership')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recorded_organization_membership_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated')], max_length=32)),
                ('capture_source', models.CharField(choices=[('auth_bootstrap', 'Auth Bootstrap'), ('manual_ui', 'Manual UI'), ('manual_api', 'Manual API'), ('system', 'System')], max_length=32)),
                ('source_reference', models.CharField(blank=True, default='', max_length=128)),
                ('note', models.TextField(blank=True, default='')),
                ('snapshot_json', models.JSONField(default=dict)),
                ('metadata_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organization_records', to='core.organization')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recorded_organization_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
