# Generated by Django 6.0.2 on 2026-02-23 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_organizationmembershiprecord_organizationrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated')], max_length=32)),
                ('capture_source', models.CharField(choices=[('manual_ui', 'Manual UI'), ('manual_api', 'Manual API'), ('import', 'Import'), ('system', 'System')], max_length=32)),
                ('source_reference', models.CharField(blank=True, default='', max_length=128)),
                ('note', models.TextField(blank=True, default='')),
                ('snapshot_json', models.JSONField(default=dict)),
                ('metadata_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LeadContactRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('status_changed', 'Status Changed'), ('converted', 'Converted'), ('deleted', 'Deleted')], max_length=32)),
                ('capture_source', models.CharField(choices=[('manual_ui', 'Manual UI'), ('manual_api', 'Manual API'), ('import', 'Import'), ('system', 'System')], max_length=32)),
                ('source_reference', models.CharField(blank=True, default='', max_length=128)),
                ('from_status', models.CharField(blank=True, choices=[('new_contact', 'New Contact'), ('qualified', 'Qualified'), ('project_created', 'Project Created'), ('archived', 'Archived')], max_length=32, null=True)),
                ('to_status', models.CharField(blank=True, choices=[('new_contact', 'New Contact'), ('qualified', 'Qualified'), ('project_created', 'Project Created'), ('archived', 'Archived')], max_length=32, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('snapshot_json', models.JSONField(default=dict)),
                ('metadata_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='leadcontact',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'project_created'), _negated=True), models.Q(('converted_customer__isnull', False), ('converted_project__isnull', False), ('converted_at__isnull', False)), _connector='OR'), name='lead_project_created_requires_conversion_links'),
        ),
        migrations.AddConstraint(
            model_name='leadcontact',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('converted_customer__isnull', True), ('converted_project__isnull', True), ('converted_at__isnull', True)), models.Q(('converted_customer__isnull', False), ('converted_project__isnull', False), ('converted_at__isnull', False)), _connector='OR'), name='lead_conversion_links_all_or_none'),
        ),
        migrations.AddConstraint(
            model_name='leadcontact',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('converted_customer__isnull', True), ('converted_project__isnull', True), ('converted_at__isnull', True)), ('status__in', ['project_created', 'archived']), _connector='OR'), name='lead_conversion_links_status_gate'),
        ),
        migrations.AddField(
            model_name='customerrecord',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='core.customer'),
        ),
        migrations.AddField(
            model_name='customerrecord',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recorded_customer_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leadcontactrecord',
            name='lead_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='core.leadcontact'),
        ),
        migrations.AddField(
            model_name='leadcontactrecord',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recorded_lead_contact_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
