# Generated by Django 6.0.2 on 2026-02-23 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_leadcontact_is_archived'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='leadcontact',
            name='lead_project_created_requires_conversion_links',
        ),
        migrations.RemoveConstraint(
            model_name='leadcontact',
            name='lead_conversion_links_status_gate',
        ),
        migrations.RemoveField(
            model_name='leadcontact',
            name='status',
        ),
    ]
