# Generated by Django 6.0.2 on 2026-02-23 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_remove_leadcontact_lead_project_created_requires_conversion_links_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customerrecord',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted')], max_length=32),
        ),
    ]
